version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DB_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    volumes:
      - mongodb-data:/data/db
    ports:
      - "${DB_MONGODB_PORT}:27017"


volumes:
  mysql-data:
  mongodb-data:
